name: Bug Report
description: Report a bug or issue in C8Store
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug!

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens
      placeholder: Describe what actually happens...
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: e.g., macOS 14.0, Ubuntu 22.04, Windows 11
      placeholder: OS version
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: C8Store Version
      description: e.g., 1.0.0
      placeholder: Version
    validations:
      required: true

  - type: input
    id: flutter-version
    attributes:
      label: Flutter Version
      description: Run `flutter --version` to get this information
      placeholder: Flutter version
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: Drag and drop screenshots here...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, paste relevant logs here
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information...
    validations:
      required: false
