// Mocks generated by Mockito 5.4.6 from annotations
// in c8store/test/screens/welcome_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:c8store/models/connection_state.dart' as _i6;
import 'package:c8store/models/oauth_credentials.dart' as _i4;
import 'package:c8store/services/oauth_service.dart' as _i2;
import 'package:c8store/services/secure_storage_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOAuthConfig_0 extends _i1.SmartFake implements _i2.OAuthConfig {
  _FakeOAuthConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSecureStorageService_1 extends _i1.SmartFake
    implements _i3.SecureStorageService {
  _FakeSecureStorageService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOAuthCredentials_2 extends _i1.SmartFake
    implements _i4.OAuthCredentials {
  _FakeOAuthCredentials_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i3.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> storeCredentials(_i4.OAuthCredentials? credentials) =>
      (super.noSuchMethod(
            Invocation.method(#storeCredentials, [credentials]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i4.OAuthCredentials?> getCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#getCredentials, []),
            returnValue: _i5.Future<_i4.OAuthCredentials?>.value(),
          )
          as _i5.Future<_i4.OAuthCredentials?>);

  @override
  _i5.Future<void> storeConnectionState(_i6.ConnectionState? state) =>
      (super.noSuchMethod(
            Invocation.method(#storeConnectionState, [state]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.ConnectionState?> getConnectionState() =>
      (super.noSuchMethod(
            Invocation.method(#getConnectionState, []),
            returnValue: _i5.Future<_i6.ConnectionState?>.value(),
          )
          as _i5.Future<_i6.ConnectionState?>);

  @override
  _i5.Future<void> storeData(String? key, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#storeData, [key, data]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>?> getData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getData, [key]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> clearCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#clearCredentials, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearConnectionState() =>
      (super.noSuchMethod(
            Invocation.method(#clearConnectionState, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#clearData, [key]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> hasData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#hasData, [key]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<String>> getAllKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getAllKeys, []),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);
}

/// A class which mocks [OAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOAuthService extends _i1.Mock implements _i2.OAuthService {
  MockOAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OAuthConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeOAuthConfig_0(this, Invocation.getter(#config)),
          )
          as _i2.OAuthConfig);

  @override
  _i3.SecureStorageService get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSecureStorageService_1(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i3.SecureStorageService);

  @override
  _i5.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<_i4.OAuthCredentials> login() =>
      (super.noSuchMethod(
            Invocation.method(#login, []),
            returnValue: _i5.Future<_i4.OAuthCredentials>.value(
              _FakeOAuthCredentials_2(this, Invocation.method(#login, [])),
            ),
          )
          as _i5.Future<_i4.OAuthCredentials>);

  @override
  _i5.Future<void> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
